In [1]:

import pandas as pd
import numpy as np

from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

In [2]:
students_marks_path = Path(r"C:\Users\User\Desktop\Final Year Project\Data\Students_Marks.xlsx")

xls = pd.ExcelFile(students_marks_path)
sheet_names = xls.sheet_names
sheet_names

['CP1_Y1S1',
 'CP2_Y1S2',
 'CP3_Y2S1',
 'CP4_Y2S2',
 'CP5_Y3S1',
 'CP6_Y3S2',
 'CP7_Y4S1',
 'CP8_Y4S2']

In [ ]:
# load checkpoint 
def load_checkpoint(sheet_name: str) -> pd.DataFrame:
    df = pd.read_excel(students_marks_path, sheet_name=sheet_name)
    
    # Keep rows with label
    df = df.dropna(subset=["RISK_BAND"]).copy()
    
    # Standardize target text JIC
    df["RISK_BAND"] = df["RISK_BAND"].astype(str).str.strip()
    
    return df

df_cp1 = load_checkpoint("CP1_Y1S1")
df_cp1.shape, df_cp1["RISK_BAND"].value_counts()

((556, 31),
 RISK_BAND
 Moderate     193
 Risk         152
 Safe         151
 Very Safe     44
 High Risk     16
 Name: count, dtype: int64)

In [ ]:
# features (X) and label (y)
DROP_COLS = ["REGNO", "RISK_BAND", "checkpoint_sheet"]  # checkpoint_sheet is text

def split_xy(df: pd.DataFrame):
    y = df["RISK_BAND"].astype(str).str.strip()

    X = df.drop(columns=[c for c in DROP_COLS if c in df.columns])

    # Keep only numeric columns 
    X = X.select_dtypes(include=[np.number])

    return X, y

In [ ]:

# Baselines :
models = {
    "LogReg": Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("clf", LogisticRegression(max_iter=2000, class_weight="balanced", multi_class="auto"))
    ]),
    
    "RandomForest": Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("clf", RandomForestClassifier(
            n_estimators=400,
            random_state=42,
            class_weight="balanced_subsample"
        ))
    ]),
    
    "HistGB": Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("clf", HistGradientBoostingClassifier(
            random_state=42
        ))
    ]),
}

In [ ]:

# Use macro F1 for multiclass imbalance 
F1_AVG = "macro"   

def evaluate_one_checkpoint(df: pd.DataFrame, test_size=0.2, random_state=42):
    X, y = split_xy(df)

    # class proportions similar in train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=test_size,
        random_state=random_state,
        stratify=y
    )

    results = []
    fitted = {}

    for name, model in models.items():
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)
        f1  = f1_score(y_test, y_pred, average=F1_AVG)

        results.append({
            "model": name,
            "accuracy": acc,
            f"f1_{F1_AVG}": f1,
            "n_train": len(X_train),
            "n_test": len(X_test)
        })
        fitted[name] = (model, X_test, y_test, y_pred)

    results_df = pd.DataFrame(results).sort_values(by=[f"f1_{F1_AVG}", "accuracy"], ascending=False)
    return results_df, fitted

In [ ]:
# CP1_Y1S1
df_cp1 = load_checkpoint("CP1_Y1S1")
res_cp1, fitted_cp1 = evaluate_one_checkpoint(df_cp1)

res_cp1

C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

          model  accuracy  f1_macro  n_train  n_test
1  RandomForest  0.500000  0.396137      444     112
2        HistGB  0.500000  0.386737      444     112
0        LogReg  0.401786  0.342262      444     112

In [ ]:
# report for the best CP1 model
best_model_name = res_cp1.iloc[0]["model"]
model, X_test, y_test, y_pred = fitted_cp1[best_model_name]

print("Best CP1 model:", best_model_name)
print(classification_report(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

Best CP1 model: RandomForest
              precision    recall  f1-score   support

   High Risk       0.00      0.00      0.00         3
    Moderate       0.43      0.41      0.42        39
        Risk       0.58      0.61      0.59        31
        Safe       0.49      0.60      0.54        30
   Very Safe       0.60      0.33      0.43         9

    accuracy                           0.50       112
   macro avg       0.42      0.39      0.40       112
weighted avg       0.49      0.50      0.49       112

Confusion matrix:
 [[ 0  2  1  0  0]
 [ 0 16 11 12  0]
 [ 0 10 19  2  0]
 [ 0  8  2 18  2]
 [ 0  1  0  5  3]]

C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [13]:
#  (CP1..CP8)
cp_sheets = [s for s in sheet_names if s.startswith("CP")]
cp_sheets

['CP1_Y1S1',
 'CP2_Y1S2',
 'CP3_Y2S1',
 'CP4_Y2S2',
 'CP5_Y3S1',
 'CP6_Y3S2',
 'CP7_Y4S1',
 'CP8_Y4S2']

In [ ]:
# Evaluate rank by F1 then Accuracy
all_results = []

for sh in cp_sheets:
    df_cp = load_checkpoint(sh)
    res_df, _ = evaluate_one_checkpoint(df_cp)

    #best model for that checkpoint
    best_row = res_df.iloc[0].to_dict()
    best_row["checkpoint"] = sh
    all_results.append(best_row)

results_all = pd.DataFrame(all_results)

results_all["cp_num"] = results_all["checkpoint"].str.extract(r"CP(\d+)").astype(int)

results_all_sorted = results_all.sort_values(
    by=[f"f1_{F1_AVG}", "accuracy", "cp_num"],
    ascending=[False, False, True]
)

results_all_sorted

C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\impute\_base.py:577: UserWarning: Skipping features without any observed values: ['wavg_mark_L4']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

          model  accuracy  f1_macro  n_train  n_test checkpoint  cp_num
7        LogReg  0.741935  0.748838      616     155   CP8_Y4S2       8
6        LogReg  0.690323  0.706387      616     155   CP7_Y4S1       7
5        LogReg  0.625806  0.632363      616     155   CP6_Y3S2       6
4        LogReg  0.632258  0.610848      616     155   CP5_Y3S1       5
3        LogReg  0.600000  0.579631      616     155   CP4_Y2S2       4
2        LogReg  0.600000  0.551185      616     155   CP3_Y2S1       3
1        HistGB  0.535484  0.502799      616     155   CP2_Y1S2       2
0  RandomForest  0.500000  0.396137      444     112   CP1_Y1S1       1

In [ ]:
#  Earliest checkpoint among the best performers
best_f1 = results_all_sorted.iloc[0][f"f1_{F1_AVG}"]

# Keep all checkpoints within a tiny tolerance of the best 
TOL = 0.005  
top_group = results_all_sorted[results_all_sorted[f"f1_{F1_AVG}"] >= best_f1 - TOL].copy()

# choose earliest checkpoint 
top_group = top_group.sort_values(by=["cp_num", f"f1_{F1_AVG}", "accuracy"], ascending=[True, False, False])

top_group.head(10), best_f1

(    model  accuracy  f1_macro  n_train  n_test checkpoint  cp_num
 7  LogReg  0.741935  0.748838      616     155   CP8_Y4S2       8,
 0.7488375025614351)

In [ ]:

best_overall = results_all_sorted.iloc[0]
best_early   = top_group.iloc[0]

print("=== Best overall checkpoint (max F1) ===")
print(best_overall[["checkpoint", "model", f"f1_{F1_AVG}", "accuracy"]])

print("\n=== Earliest checkpoint within tolerance of best F1 ===")
print(best_early[["checkpoint", "model", f"f1_{F1_AVG}", "accuracy"]])

=== Best overall checkpoint (max F1) ===
checkpoint    CP8_Y4S2
model           LogReg
f1_macro      0.748838
accuracy      0.741935
Name: 7, dtype: object

=== Earliest checkpoint within tolerance of best F1 ===
checkpoint    CP8_Y4S2
model           LogReg
f1_macro      0.748838
accuracy      0.741935
Name: 7, dtype: object

pycaret

In [ ]:

import pandas as pd
import numpy as np

from pycaret.classification import ClassificationExperiment
from sklearn.metrics import f1_score

file_path = r"C:\Users\User\Desktop\Final Year Project\Data\Students_Marks.xlsx"

In [ ]:
# load checkpoint sheet
def load_cp(sheet_name: str) -> pd.DataFrame:
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    df = df.dropna(subset=["RISK_BAND"]).copy()

    return df

In [ ]:
# Compare models CP1 only ranked by Macro F1
df_cp1 = pd.read_excel(file_path, sheet_name="CP1_Y1S1")
df_cp1 = df_cp1.dropna(subset=["RISK_BAND"]).copy()

exp = ClassificationExperiment()
exp.setup(
    data=df_cp1,
    target="RISK_BAND",
    ignore_features=["REGNO", "checkpoint_sheet"],
    session_id=42,
    fold=5,
    fold_shuffle=True,
    verbose=False
)

best_cp1 = exp.compare_models(sort="F1")   # <-- ranked by F1
lb_cp1 = exp.pull()

lb_cp1.head(15)

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
lr,Logistic Regression,0.5165,0.0000,0.5165,0.5234,0.5126,0.3202,0.3222,0.192
rf,Random Forest Classifier,0.5193,0.7609,0.5193,0.5213,0.5103,0.3201,0.3244,0.114
lda,Linear Discriminant Analysis,0.4988,0.0000,0.4988,0.5224,0.4977,0.2990,0.3016,0.028
lightgbm,Light Gradient Boosting Machine,0.5014,0.7291,0.5014,0.4796,0.4864,0.2975,0.2997,0.790
ridge,Ridge Classifier,0.4910,0.0000,0.4910,0.4924,0.4713,0.2734,0.2778,0.022
et,Extra Trees Classifier,0.4783,0.7350,0.4783,0.4812,0.4701,0.2690,0.2714,0.160
knn,K Neighbors Classifier,0.4626,0.6822,0.4626,0.4791,0.4451,0.2239,0.2328,0.034
gbc,Gradient Boosting Classifier,0.4449,0.0000,0.4449,0.4309,0.4345,0.2233,0.2247,0.404
dt,Decision Tree Classifier,0.4242,0.5975,0.4242,0.4142,0.4170,0.2000,0.2010,0.022
ada,Ada Boost Classifier,0.4139,0.0000,0.4139,0.4114,0.3736,0.2075,0.2220,0.130
nb,Naive Bayes,0.3083,0.6618,0.3083,0.3976,0.2772,0.1469,0.1684,0.022
qda,Quadratic Discriminant Analysis,0.3522,0.0000,0.3522,0.1751,0.2047,0.0163,0.0210,0.020
dummy,Dummy Classifier,0.3471,0.5000,0.3471,0.1204,0.1788,0.0000,0.0000,0.024
svm,SVM - Linear Kernel,0.3033,0.0000,0.3033,0.0932,0.1422,0.0000,0.0000,0.030

In [ ]:
#  CP1 leaderboard sorted by f1_macro
leaderboard_cp1.sort_values("F1 Macro", ascending=False).head(30)

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,F1 Macro,TT (Sec)
lr,Logistic Regression,0.5165,0.0000,0.5165,0.5234,0.5126,0.3202,0.3222,0.0,2.068
knn,K Neighbors Classifier,0.4626,0.6822,0.4626,0.4791,0.4451,0.2239,0.2328,0.0,0.608
nb,Naive Bayes,0.3083,0.6618,0.3083,0.3976,0.2772,0.1469,0.1684,0.0,0.018
dt,Decision Tree Classifier,0.4242,0.5975,0.4242,0.4142,0.4170,0.2000,0.2010,0.0,0.016
svm,SVM - Linear Kernel,0.3033,0.0000,0.3033,0.0932,0.1422,0.0000,0.0000,0.0,0.036
ridge,Ridge Classifier,0.4910,0.0000,0.4910,0.4924,0.4713,0.2734,0.2778,0.0,0.020
rf,Random Forest Classifier,0.5193,0.7609,0.5193,0.5213,0.5103,0.3201,0.3244,0.0,0.084
qda,Quadratic Discriminant Analysis,0.3522,0.0000,0.3522,0.1751,0.2047,0.0163,0.0210,0.0,0.020
ada,Ada Boost Classifier,0.4139,0.0000,0.4139,0.4114,0.3736,0.2075,0.2220,0.0,0.046
gbc,Gradient Boosting Classifier,0.4449,0.0000,0.4449,0.4309,0.4345,0.2233,0.2247,0.0,0.296
lda,Linear Discriminant Analysis,0.4988,0.0000,0.4988,0.5224,0.4977,0.2990,0.3016,0.0,0.016
et,Extra Trees Classifier,0.4783,0.7350,0.4783,0.4812,0.4701,0.2690,0.2714,0.0,0.102
lightgbm,Light Gradient Boosting Machine,0.5014,0.7291,0.5014,0.4796,0.4864,0.2975,0.2997,0.0,0.352
dummy,Dummy Classifier,0.3471,0.5000,0.3471,0.1204,0.1788,0.0000,0.0000,0.0,0.020

In [4]:
xls = pd.ExcelFile(file_path)
cp_sheets = [s for s in xls.sheet_names if s.startswith("CP")]
cp_sheets

['CP1_Y1S1',
 'CP2_Y1S2',
 'CP3_Y2S1',
 'CP4_Y2S2',
 'CP5_Y3S1',
 'CP6_Y3S2',
 'CP7_Y4S1',
 'CP8_Y4S2']

In [ ]:
# record the best model best macro F1
results = []

for sh in cp_sheets:
    df = pd.read_excel(file_path, sheet_name=sh).dropna(subset=["RISK_BAND"]).copy()

    exp = ClassificationExperiment()
    exp.setup(
        data=df,
        target="RISK_BAND",
        ignore_features=["REGNO", "checkpoint_sheet"],
        session_id=42,
        fold=5,
        fold_shuffle=True,
        verbose=False
    )

    best = exp.compare_models(sort="F1")
    lb = exp.pull()


    lb_sorted = lb.sort_values(by=["F1", "Accuracy"], ascending=False)
    top = lb_sorted.iloc[0]

    cp_num = int(sh.split("_")[0].replace("CP", ""))

    results.append({
        "checkpoint": sh,
        "cp_num": cp_num,
        "best_model": top["Model"],
        "f1": float(top["F1"]),
        "accuracy": float(top["Accuracy"])
    })

results_df = pd.DataFrame(results).sort_values(
    by=["f1", "accuracy", "cp_num"],
    ascending=[False, False, True]
).reset_index(drop=True)

results_df

  checkpoint  cp_num                    best_model      f1  accuracy
0   CP8_Y4S2       8      Random Forest Classifier  0.8067    0.8145
1   CP7_Y4S1       7  Linear Discriminant Analysis  0.7572    0.7587
2   CP5_Y3S1       5  Linear Discriminant Analysis  0.7279    0.7273
3   CP6_Y3S2       6  Linear Discriminant Analysis  0.7243    0.7253
4   CP4_Y2S2       4  Linear Discriminant Analysis  0.6820    0.6846
5   CP3_Y2S1       3      Random Forest Classifier  0.6185    0.6270
6   CP2_Y1S2       2      Random Forest Classifier  0.5490    0.5584
7   CP1_Y1S1       1           Logistic Regression  0.5126    0.5165

In [ ]:
#Pick earliest checkpoint near-best
best_f1 = results_df.loc[0, "f1_macro"]

TOL = 0.01  
near_best = results_df[results_df["f1_macro"] >= best_f1 - TOL].copy()
near_best = near_best.sort_values(by=["cp_num", "f1_macro", "accuracy"], ascending=[True, False, False])

print("Best overall:")
print(results_df.iloc[0])

print("\nEarliest checkpoint within tolerance:")
print(near_best.iloc[0])

Best overall:
checkpoint               CP8_Y4S2
cp_num                          8
best_model    Logistic Regression
f1_macro                      0.0
accuracy                   0.7458
Name: 0, dtype: object

Earliest checkpoint within tolerance:
checkpoint               CP1_Y1S1
cp_num                          1
best_model    Logistic Regression
f1_macro                      0.0
accuracy                   0.5165
Name: 7, dtype: object

In [ ]:
# Loop checkpoints and record best model per checkpoint
from pycaret.classification import ClassificationExperiment
from sklearn.metrics import f1_score
import pandas as pd

results = []

for sh in cp_sheets:
    df = load_cp(sh)

    exp = ClassificationExperiment()
    exp.setup(
        data=df,
        target="RISK_BAND",
        ignore_features=["REGNO", "checkpoint_sheet"],
        session_id=42,
        fold=5,
        fold_shuffle=True,
        verbose=False
    )

   
    exp.add_metric(
        id="f1_macro",
        name="F1 Macro",
        score_func=f1_score,
        average="macro"
    )

   
    best = exp.compare_models(sort="Accuracy")
    lb = exp.pull()

    
    lb_sorted = lb.sort_values(by=["Accuracy", "F1 Macro"], ascending=False)
    top = lb_sorted.iloc[0]

    cp_num = int(sh.split("_")[0].replace("CP", ""))

    results.append({
        "checkpoint": sh,
        "cp_num": cp_num,
        "best_model": top["Model"],
        "accuracy": float(top["Accuracy"]),
        "f1_macro": float(top["F1 Macro"]),
    })

results_df = pd.DataFrame(results).sort_values(
    by=["accuracy", "f1_macro", "cp_num"],
    ascending=[False, False, True]
).reset_index(drop=True)

results_df

  checkpoint  cp_num                    best_model  accuracy  f1_macro
0   CP8_Y4S2       8      Random Forest Classifier    0.8145       0.0
1   CP7_Y4S1       7  Linear Discriminant Analysis    0.7587       0.0
2   CP5_Y3S1       5  Linear Discriminant Analysis    0.7273       0.0
3   CP6_Y3S2       6      Random Forest Classifier    0.7272       0.0
4   CP4_Y2S2       4  Linear Discriminant Analysis    0.6846       0.0
5   CP3_Y2S1       3      Random Forest Classifier    0.6270       0.0
6   CP2_Y1S2       2      Random Forest Classifier    0.5584       0.0
7   CP1_Y1S1       1      Random Forest Classifier    0.5193       0.0

In [ ]:
#  Pick earliest checkpoint 
best_f1 = results_df.loc[0, "f1"]
TOL = 0.01  
near_best = results_df[results_df["f1"] >= best_f1 - TOL].copy()
near_best = near_best.sort_values(by=["cp_num", "f1", "accuracy"], ascending=[True, False, False])

print("Best overall by F1:")
print(results_df.iloc[0])

print("\nEarliest checkpoint within tolerance:")
print(near_best.iloc[0])

Best overall by F1:
checkpoint                    CP8_Y4S2
cp_num                               8
best_model    Random Forest Classifier
f1                              0.8067
accuracy                        0.8145
Name: 0, dtype: object

Earliest checkpoint within tolerance:
checkpoint                    CP8_Y4S2
cp_num                               8
best_model    Random Forest Classifier
f1                              0.8067
accuracy                        0.8145
Name: 0, dtype: object