In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

Libraries imported successfully!

In [ ]:

df_admission = pd.read_excel(r"C:\Users\User\Desktop\Final Year Project\Data\AdmissionResults.xls")
df_personal  = pd.read_excel(r"C:\Users\User\Desktop\Final Year Project\Data\ListOfStudPersDetails.xlsx")
df_transcript = pd.read_excel(r"C:\Users\User\Desktop\Final Year Project\Data\Transcript.xlsx")
df_cgpa = pd.read_excel(r"C:\Users\User\Desktop\Final Year Project\Data\Transcript_cgpa.xlsx")

All datasets loaded successfully!

In [9]:
# Display the first 5 rows
print("First 5 rows of the dataset:")
print("Admission:")
display(df_admission.head())
print("")
print("personal:")
display(df_personal.head())
print("")
print("transcript:")
display(df_transcript.head())
print("")
print("cgpa:")
display(df_cgpa.head())
print("")

# Get a summary of the DataFrame, including data types and non-null values
print("\nDataset Info:")
print("Admission:")
df_admission.info()
print("")
print("personal:")
df_personal.info()
print("")
print("transcript:")
df_transcript.info()
print("")
print("cgpa:")
df_cgpa.info()
print("")


# Check for missing values in each column
print("\nMissing values per column:")
print("Admission:")
print(df_admission.isnull().sum())
print("")
print("personal:")
print(df_personal.isnull().sum())
print("")
print("transcript:")
print(df_transcript.isnull().sum())
print("")
print("cgpa:")
print(df_cgpa.isnull().sum())
print("")

First 5 rows of the dataset:
Admission:

,APP_TYPE,FIRST_CHOISE_NAME,SECOND_CHOISE_NAME,PROCESS_CHOISE_NAME,STU_REG_NO,CONFIRM_STATUS,APPLICANT_INTENTION,EDU_YEAR,SUBJECT,GRADE,MEDIUM
0,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,101075.0,Accepted,Accept,2020,Physics,8,English
1,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,101075.0,Accepted,Accept,2019,8001-General Paper,D,English
2,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,101075.0,Accepted,Accept,2020,9626-Information Technology,E,English
3,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,101075.0,Accepted,Accept,2020,Mathematics,8,English
4,UNDERGRA,Bachelor of Science,Bachelor of Engineering,Bachelor of Science,NaN,Accepted,NaN,2021,7405-Chemistry,A,English

personal:

,Faculty,Degree Type,Status,Reg No,Title,Gender,Degree,Date of Birth,Citizenship,Race,Religion,Funding,Year Joined,Part Time,Major code,Major name,Minor,First Registered,Last Registered
0,FASS,Bachelor,Graduating,100001,AWG,M,Bachelor of Arts,Jan-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
1,FASS,Bachelor,Graduating,100002,DYG,F,Bachelor of Arts,Jan-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
2,FASS,Bachelor,Graduating,100003,DYG,F,Bachelor of Arts,Dec-00,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
3,FASS,Bachelor,Graduating,100004,DYG,F,Bachelor of Arts,Aug-00,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AW,"Geography, Environment and Development",NaN,Y1 S1,Y4 S2
4,FASS,Bachelor,Active,100005,DYG,F,Bachelor of Arts,Aug-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AZ,Sociology and Anthropology,NaN,Y1 S1,Y5 S1

transcript:

,REGNO,MODULE_CODE,MODULE_NAME,PASS_FAIL,MODULE_ACADEMIC_REMARKS,MC,GPA_CALC,CGPA_CALC,MARKS,P_C_W,C_W,SGPA_CALC,GRADE_NAME,GRADE_PTS,LEVEL_WEIGHT
0,100001,PB-1501,MELAYU ISLAM BERAJA,PASS,NaN,4,Y,Y,73.0,2.4,0.8,Y,C+,3.0,0.2
1,100001,LE-1503,ACADEMIC READING AND WRITING SKILLS,PASS,NaN,4,Y,Y,66.3,2.4,0.8,Y,C+,3.0,0.2
2,100001,AH-2309,INDONESIA IN THE 20TH CENTURY FROM A POLITICAL...,PASS,NaN,4,Y,Y,51.2,1.2,0.8,Y,D,1.5,0.2
3,100001,AH-1201,THE STATE AND SOCIETY IN WORLD CIVILIZATIONS,PASS,NaN,4,Y,Y,67.3,2.4,0.8,Y,C+,3.0,0.2
4,100002,AH-1201,THE STATE AND SOCIETY IN WORLD CIVILIZATIONS,PASS,NaN,4,Y,Y,62.6,2.0,0.8,Y,C,2.5,0.2

cgpa:

    REGNO   GPA  CGPA  AWARDED_MCS
0  100001  3.61  3.06         20.0
1  100002  2.40  2.81         20.0
2  100003  3.88  3.17         16.0
3  100004  3.13  3.69         16.0
4  100005  2.13  2.55         20.0

Dataset Info:
Admission:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4810 entries, 0 to 4809
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   APP_TYPE             4810 non-null   object
 1   FIRST_CHOISE_NAME    4810 non-null   object
 2   SECOND_CHOISE_NAME   4810 non-null   object
 3   PROCESS_CHOISE_NAME  4810 non-null   object
 4   STU_REG_NO           2539 non-null   float64
 5   CONFIRM_STATUS       4810 non-null   object
 6   APPLICANT_INTENTION  2752 non-null   object
 7   EDU_YEAR             4810 non-null   int64
 8   SUBJECT              4810 non-null   object
 9   GRADE                4807 non-null   object
 10  MEDIUM               4810 non-null   object
dtypes: float64(1), int64(1), object(9)
memory usage: 413.5+ KB

personal:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Faculty           850 non-null    object
 1   Degree Type       850 non-null    object
 2   Status            850 non-null    object
 3   Reg No            850 non-null    int64
 4   Title             850 non-null    object
 5   Gender            850 non-null    object
 6   Degree            850 non-null    object
 7   Date of Birth     850 non-null    object
 8   Citizenship       850 non-null    object
 9   Race              831 non-null    object
 10  Religion          845 non-null    object
 11  Funding           850 non-null    object
 12  Year Joined       850 non-null    object
 13  Part Time         850 non-null    object
 14  Major code        832 non-null    object
 15  Major name        850 non-null    object
 16  Minor             4 non-null      object
 17  First Registered  850 non-null    object
 18  Last Registered   850 non-null    object
dtypes: int64(1), object(18)
memory usage: 126.3+ KB

transcript:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2976 entries, 0 to 2975
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   REGNO                    2976 non-null   int64
 1   MODULE_CODE              2976 non-null   object
 2   MODULE_NAME              2976 non-null   object
 3   PASS_FAIL                2934 non-null   object
 4   MODULE_ACADEMIC_REMARKS  96 non-null     object
 5   MC                       2976 non-null   int64
 6   GPA_CALC                 2976 non-null   object
 7   CGPA_CALC                2976 non-null   object
 8   MARKS                    2930 non-null   float64
 9   P_C_W                    2932 non-null   float64
 10  C_W                      2932 non-null   float64
 11  SGPA_CALC                2932 non-null   object
 12  GRADE_NAME               2890 non-null   object
 13  GRADE_PTS                2932 non-null   float64
 14  LEVEL_WEIGHT             2932 non-null   float64
dtypes: float64(5), int64(2), object(8)
memory usage: 348.9+ KB

cgpa:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 771 entries, 0 to 770
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   REGNO        771 non-null    int64
 1   GPA          771 non-null    float64
 2   CGPA         771 non-null    float64
 3   AWARDED_MCS  753 non-null    float64
dtypes: float64(3), int64(1)
memory usage: 24.2 KB


Missing values per column:
Admission:
APP_TYPE                  0
FIRST_CHOISE_NAME         0
SECOND_CHOISE_NAME        0
PROCESS_CHOISE_NAME       0
STU_REG_NO             2271
CONFIRM_STATUS            0
APPLICANT_INTENTION    2058
EDU_YEAR                  0
SUBJECT                   0
GRADE                     3
MEDIUM                    0
dtype: int64

personal:
Faculty               0
Degree Type           0
Status                0
Reg No                0
Title                 0
Gender                0
Degree                0
Date of Birth         0
Citizenship           0
Race                 19
Religion              5
Funding               0
Year Joined           0
Part Time             0
Major code           18
Major name            0
Minor               846
First Registered      0
Last Registered       0
dtype: int64

transcript:
REGNO                         0
MODULE_CODE                   0
MODULE_NAME                   0
PASS_FAIL                    42
MODULE_ACADEMIC_REMARKS    2880
MC                            0
GPA_CALC                      0
CGPA_CALC                     0
MARKS                        46
P_C_W                        44
C_W                          44
SGPA_CALC                    44
GRADE_NAME                   86
GRADE_PTS                    44
LEVEL_WEIGHT                 44
dtype: int64

cgpa:
REGNO           0
GPA             0
CGPA            0
AWARDED_MCS    18
dtype: int64

Dataset 1: Demographics (Personal Details).

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np


PROJECT_DIR = Path(r"C:\Users\User\Desktop\Final Year Project")
DATA_DIR    = PROJECT_DIR / "Data"
OUT_DIR     = PROJECT_DIR / r"22b6023 Muizzul" / "3 Processed Data"
OUT_DIR.mkdir(parents=True, exist_ok=True)


PERSONAL_PATH = DATA_DIR / "ListOfStudPersDetails.xlsx"

print("DATA_DIR:", DATA_DIR)
print("OUT_DIR:", OUT_DIR)

DATA_DIR: C:\Users\User\Desktop\Final Year Project\Data
OUT_DIR: C:\Users\User\Desktop\Final Year Project\22b6023 Muizzul\3 Processed Data

In [11]:
df_raw = pd.read_excel(PERSONAL_PATH)
print(df_raw.shape)
df_raw.head()

(850, 19)

,Faculty,Degree Type,Status,Reg No,Title,Gender,Degree,Date of Birth,Citizenship,Race,Religion,Funding,Year Joined,Part Time,Major code,Major name,Minor,First Registered,Last Registered
0,FASS,Bachelor,Graduating,100001,AWG,M,Bachelor of Arts,Jan-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
1,FASS,Bachelor,Graduating,100002,DYG,F,Bachelor of Arts,Jan-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
2,FASS,Bachelor,Graduating,100003,DYG,F,Bachelor of Arts,Dec-00,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
3,FASS,Bachelor,Graduating,100004,DYG,F,Bachelor of Arts,Aug-00,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AW,"Geography, Environment and Development",NaN,Y1 S1,Y4 S2
4,FASS,Bachelor,Active,100005,DYG,F,Bachelor of Arts,Aug-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AZ,Sociology and Anthropology,NaN,Y1 S1,Y5 S1

In [12]:
rename_map = {
    "Reg No": "REGNO",
    "Faculty": "Faculty",
    "Degree Type": "DegreeType",
    "Status": "Status",
    "Title": "Title",
    "Gender": "Gender",
    "Degree": "Degree",
    "Date of Birth": "DOB",
    "Citizenship": "Citizenship",
    "Race": "Race",
    "Religion": "Religion",
    "Funding": "Funding",
    "Year Joined": "YearJoined",
    "Part Time": "PartTime",
    "Major code": "MajorCode",
    "Major name": "MajorName",
    "Minor": "Minor",
    "First Registered": "FirstRegistered",
    "Last Registered": "LastRegistered",
}

cols_keep = list(rename_map.keys())
df = df_raw[cols_keep].rename(columns=rename_map)
df.head()

,REGNO,Faculty,DegreeType,Status,Title,Gender,Degree,DOB,Citizenship,Race,Religion,Funding,YearJoined,PartTime,MajorCode,MajorName,Minor,FirstRegistered,LastRegistered
0,100001,FASS,Bachelor,Graduating,AWG,M,Bachelor of Arts,Jan-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
1,100002,FASS,Bachelor,Graduating,DYG,F,Bachelor of Arts,Jan-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
2,100003,FASS,Bachelor,Graduating,DYG,F,Bachelor of Arts,Dec-00,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AH,Historical Studies,NaN,Y1 S1,Y4 S2
3,100004,FASS,Bachelor,Graduating,DYG,F,Bachelor of Arts,Aug-00,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AW,"Geography, Environment and Development",NaN,Y1 S1,Y4 S2
4,100005,FASS,Bachelor,Active,DYG,F,Bachelor of Arts,Aug-01,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,N,AZ,Sociology and Anthropology,NaN,Y1 S1,Y5 S1

In [ ]:
# whitespace
for c in df.select_dtypes(include="object").columns:
    df[c] = df[c].astype(str).str.strip()

# REGNO as nullable integer 
df["REGNO"] = pd.to_numeric(df["REGNO"], errors="coerce").astype("Int64")

# Parse date columns 
for dcol in ["DOB", "FirstRegistered", "LastRegistered"]:
    df[dcol] = pd.to_datetime(df[dcol], errors="coerce")

# Standardize Gender to {Male, Female, Unknown}
gender_map = {
    "M": "Male", "F": "Female",
    "male": "Male", "female": "Female",
    "MALE": "Male", "FEMALE": "Female"
}
df["Gender"] = df["Gender"].replace(gender_map)
df.loc[~df["Gender"].isin(["Male", "Female"]), "Gender"] = "Unknown"

# Standardize PartTime to {Yes, No, Unknown}
df["PartTime"] = df["PartTime"].str.upper().map({"YES": "Yes", "NO": "No"})
df.loc[~df["PartTime"].isin(["Yes", "No"]), "PartTime"] = "Unknown"

# Fill low-importance missing with 'Unknown'
for c in ["Race", "Religion", "Funding", "MajorCode", "Minor"]:
    df[c] = df[c].replace({None: "Unknown", "nan": "Unknown"}).fillna("Unknown")

df.head()

C:\Users\User\AppData\Local\Temp\ipykernel_16208\1950114520.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[dcol] = pd.to_datetime(df[dcol], errors="coerce")
C:\Users\User\AppData\Local\Temp\ipykernel_16208\1950114520.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[dcol] = pd.to_datetime(df[dcol], errors="coerce")
C:\Users\User\AppData\Local\Temp\ipykernel_16208\1950114520.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[dcol] = pd.to_datetime(df[dcol], errors="coerce")

,REGNO,Faculty,DegreeType,Status,Title,Gender,Degree,DOB,Citizenship,Race,Religion,Funding,YearJoined,PartTime,MajorCode,MajorName,Minor,FirstRegistered,LastRegistered
0,100001,FASS,Bachelor,Graduating,AWG,Male,Bachelor of Arts,NaT,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,Unknown,AH,Historical Studies,Unknown,NaT,NaT
1,100002,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,Unknown,AH,Historical Studies,Unknown,NaT,NaT
2,100003,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,Unknown,AH,Historical Studies,Unknown,NaT,NaT
3,100004,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,Unknown,AW,"Geography, Environment and Development",Unknown,NaT,NaT
4,100005,FASS,Bachelor,Active,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,ISLAM,GS-BRU,Y1 S1,Unknown,AZ,Sociology and Anthropology,Unknown,NaT,NaT

In [ ]:
# Drop rows without a REGNO (since we can't link them to other tables, and they are few)
df = df[~df["REGNO"].isna()].copy()

# Keep the most recent record per student
df.sort_values(["REGNO", "LastRegistered"], ascending=[True, False], inplace=True)
df = df.drop_duplicates(subset=["REGNO"], keep="first").reset_index(drop=True)

print("After dedup:", df.shape)

After dedup: (850, 19)

In [15]:
today = pd.Timestamp.today().normalize()

df["Age"] = ((today - df["DOB"]).dt.days / 365.25).round(1)
df["YearsSinceFirstReg"] = ((today - df["FirstRegistered"]).dt.days / 365.25).round(1)
df["YearsSinceLastReg"]  = ((today - df["LastRegistered"]).dt.days / 365.25).round(1)

df[["Age", "YearsSinceFirstReg", "YearsSinceLastReg"]].describe()

              Age  YearsSinceFirstReg  YearsSinceLastReg
count  193.000000                 0.0                0.0
mean    27.495337                 NaN                NaN
std      1.841430                 NaN                NaN
min     25.800000                 NaN                NaN
25%     26.100000                 NaN                NaN
50%     27.000000                 NaN                NaN
75%     28.500000                 NaN                NaN
max     40.100000                 NaN                NaN

In [16]:
print("Rows:", len(df))

print("\nNulls per column:")
print(df.isna().sum().sort_values(ascending=False))

print("\nGender distribution:")
print(df["Gender"].value_counts(dropna=False))

print("\nPartTime distribution:")
print(df["PartTime"].value_counts(dropna=False))

df.head(10)

Rows: 850

Nulls per column:
YearsSinceFirstReg    850
LastRegistered        850
FirstRegistered       850
YearsSinceLastReg     850
Age                   657
DOB                   657
Gender                  0
Title                   0
Status                  0
DegreeType              0
Faculty                 0
REGNO                   0
Citizenship             0
Degree                  0
PartTime                0
YearJoined              0
Funding                 0
Religion                0
Race                    0
Minor                   0
MajorCode               0
MajorName               0
dtype: int64

Gender distribution:
Gender
Female    558
Male      292
Name: count, dtype: int64

PartTime distribution:
PartTime
Unknown    850
Name: count, dtype: int64

,REGNO,Faculty,DegreeType,Status,Title,Gender,Degree,DOB,Citizenship,Race,...,YearJoined,PartTime,MajorCode,MajorName,Minor,FirstRegistered,LastRegistered,Age,YearsSinceFirstReg,YearsSinceLastReg
0,90030,C3L,Bachelor,Graduating,DYG,Female,Bachelor of Science in Digital Economy,1985-08-01,Bruneian,Malay,...,Y1 S1,Unknown,Unknown,,Unknown,NaT,NaT,40.1,NaN,NaN
1,100001,FASS,Bachelor,Graduating,AWG,Male,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AH,Historical Studies,Unknown,NaT,NaT,NaN,NaN,NaN
2,100002,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AH,Historical Studies,Unknown,NaT,NaT,NaN,NaN,NaN
3,100003,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AH,Historical Studies,Unknown,NaT,NaT,NaN,NaN,NaN
4,100004,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AW,"Geography, Environment and Development",Unknown,NaT,NaT,NaN,NaN,NaN
5,100005,FASS,Bachelor,Active,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AZ,Sociology and Anthropology,Unknown,NaT,NaT,NaN,NaN,NaN
6,100006,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AN,English Studies,Unknown,NaT,NaT,NaN,NaN,NaN
7,100007,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AW,"Geography, Environment and Development",Unknown,NaT,NaT,NaN,NaN,NaN
8,100008,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AW,"Geography, Environment and Development",Unknown,NaT,NaT,NaN,NaN,NaN
9,100009,FASS,Bachelor,Graduating,DYG,Female,Bachelor of Arts,NaT,Bruneian,Malay,...,Y1 S1,Unknown,AZ,Sociology and Anthropology,Unknown,NaT,NaT,NaN,NaN,NaN

In [17]:
out_path = OUT_DIR / "personal_clean.csv"
df.to_csv(out_path, index=False)
print("Saved:", out_path)

Saved: C:\Users\User\Desktop\Final Year Project\22b6023 Muizzul\3 Processed Data\personal_clean.csv

Admission Dataset Preprocessing

In [18]:
from pathlib import Path
import pandas as pd
import numpy as np

# --- Folders ---
PROJECT_DIR = Path(r"C:\Users\User\Desktop\Final Year Project")
DATA_DIR    = PROJECT_DIR / "Data"
OUT_DIR     = PROJECT_DIR / r"22b6023 Muizzul" / "3 Processed Data"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# --- Files ---
ADMISSION_PATH = DATA_DIR / "AdmissionResults.xls"

print("Reading:", ADMISSION_PATH)
print("Saving to:", OUT_DIR)

Reading: C:\Users\User\Desktop\Final Year Project\Data\AdmissionResults.xls
Saving to: C:\Users\User\Desktop\Final Year Project\22b6023 Muizzul\3 Processed Data

In [19]:
df_raw = pd.read_excel(ADMISSION_PATH)
print(df_raw.shape)
df_raw.head()

(4810, 11)

,APP_TYPE,FIRST_CHOISE_NAME,SECOND_CHOISE_NAME,PROCESS_CHOISE_NAME,STU_REG_NO,CONFIRM_STATUS,APPLICANT_INTENTION,EDU_YEAR,SUBJECT,GRADE,MEDIUM
0,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,101075.0,Accepted,Accept,2020,Physics,8,English
1,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,101075.0,Accepted,Accept,2019,8001-General Paper,D,English
2,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,101075.0,Accepted,Accept,2020,9626-Information Technology,E,English
3,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,101075.0,Accepted,Accept,2020,Mathematics,8,English
4,UNDERGRA,Bachelor of Science,Bachelor of Engineering,Bachelor of Science,NaN,Accepted,NaN,2021,7405-Chemistry,A,English

In [20]:
rename_map = {
    "STU_REG_NO": "REGNO",
    "APP_TYPE": "AppType",
    "FIRST_CHOISE_NAME": "FirstChoice",
    "SECOND_CHOISE_NAME": "SecondChoice",
    "PROCESS_CHOISE_NAME": "ProcessChoice",
    "CONFIRM_STATUS": "ConfirmStatus",
    "APPLICANT_INTENTION": "ApplicantIntention",
    "EDU_YEAR": "EduYear",
    "SUBJECT": "Subject",
    "GRADE": "Grade",
    "MEDIUM": "Medium"
}

df = df_raw.rename(columns=rename_map)[list(rename_map.values())]
df.head()

,REGNO,AppType,FirstChoice,SecondChoice,ProcessChoice,ConfirmStatus,ApplicantIntention,EduYear,Subject,Grade,Medium
0,101075.0,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,Accepted,Accept,2020,Physics,8,English
1,101075.0,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,Accepted,Accept,2019,8001-General Paper,D,English
2,101075.0,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,Accepted,Accept,2020,9626-Information Technology,E,English
3,101075.0,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,Accepted,Accept,2020,Mathematics,8,English
4,NaN,UNDERGRA,Bachelor of Science,Bachelor of Engineering,Bachelor of Science,Accepted,NaN,2021,7405-Chemistry,A,English

In [ ]:
# Drop rows without REG
df = df[~df["REGNO"].isna()].copy()

# Ensure REGNO nteger
df["REGNO"] = pd.to_numeric(df["REGNO"], errors="coerce").astype("Int64")

# Fill missing categorical values
for col in ["Grade", "ApplicantIntention"]:
    df[col] = df[col].fillna("Unknown").astype(str).str.strip()

df.head()

,REGNO,AppType,FirstChoice,SecondChoice,ProcessChoice,ConfirmStatus,ApplicantIntention,EduYear,Subject,Grade,Medium
0,101075,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,Accepted,Accept,2020,Physics,8,English
1,101075,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,Accepted,Accept,2019,8001-General Paper,D,English
2,101075,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,Accepted,Accept,2020,9626-Information Technology,E,English
3,101075,UNDERGRA,Bachelor of Business,Bachelor of Science,Bachelor of Business,Accepted,Accept,2020,Mathematics,8,English
8,102137,UNDERGRA,Bachelor of Health Science,Bachelor of Science,Bachelor of Science,Accepted,Accept,2020,Mathematics,8,ENGLISH

???????????

In [22]:
print("all unique values")
df["Grade"].unique()
print("frequent each grade")
df["Grade"].value_counts()

all unique values
frequent each grade

Grade
7                   608
8                   602
9                   412
12                  329
10                  228
11                   80
D                    48
C                    45
E                    34
B                    29
d                    27
c                    22
e                    16
A                    15
A*                   13
b                    12
a                     5
Predicted A           3
A* (PREDICTED)        3
A (Predicted)         2
A (predicted)         2
A* (predicted)        1
A* (achieved)         1
A* (Predicted)        1
HIGH DISTINCTION      1
Name: count, dtype: int64

Transcript Records preprocessing

In [ ]:
from pathlib import Path
import pandas as pd
import numpy as np


PROJECT_DIR = Path(r"C:\Users\User\Desktop\Final Year Project")
DATA_DIR    = PROJECT_DIR / "Data"
OUT_DIR     = PROJECT_DIR / r"22b6023 Muizzul" / "3 Processed Data"
OUT_DIR.mkdir(parents=True, exist_ok=True)


TRANSCRIPT_PATH = DATA_DIR / "Transcript.xlsx"

print("Reading:", TRANSCRIPT_PATH)
print("Saving to:", OUT_DIR)

Reading: C:\Users\User\Desktop\Final Year Project\Data\Transcript.xlsx
Saving to: C:\Users\User\Desktop\Final Year Project\22b6023 Muizzul\3 Processed Data

In [24]:
df_raw = pd.read_excel(TRANSCRIPT_PATH)
print(df_raw.shape)
df_raw.head()

(2976, 15)

,REGNO,MODULE_CODE,MODULE_NAME,PASS_FAIL,MODULE_ACADEMIC_REMARKS,MC,GPA_CALC,CGPA_CALC,MARKS,P_C_W,C_W,SGPA_CALC,GRADE_NAME,GRADE_PTS,LEVEL_WEIGHT
0,100001,PB-1501,MELAYU ISLAM BERAJA,PASS,NaN,4,Y,Y,73.0,2.4,0.8,Y,C+,3.0,0.2
1,100001,LE-1503,ACADEMIC READING AND WRITING SKILLS,PASS,NaN,4,Y,Y,66.3,2.4,0.8,Y,C+,3.0,0.2
2,100001,AH-2309,INDONESIA IN THE 20TH CENTURY FROM A POLITICAL...,PASS,NaN,4,Y,Y,51.2,1.2,0.8,Y,D,1.5,0.2
3,100001,AH-1201,THE STATE AND SOCIETY IN WORLD CIVILIZATIONS,PASS,NaN,4,Y,Y,67.3,2.4,0.8,Y,C+,3.0,0.2
4,100002,AH-1201,THE STATE AND SOCIETY IN WORLD CIVILIZATIONS,PASS,NaN,4,Y,Y,62.6,2.0,0.8,Y,C,2.5,0.2

In [25]:
rename_map = {
    "REGNO": "REGNO",
    "MODULE_CODE": "ModuleCode",
    "MODULE_NAME": "ModuleName",
    "PASS_FAIL": "PassFail",
    "MODULE_ACADEMIC_REMARKS": "Remarks",
    "MC": "MC",
    "GPA_CALC": "GPA_calc",
    "CGPA_CALC": "CGPA_calc",
    "MARKS": "Marks",
    "P_C_W": "PracticalCW",
    "C_W": "Coursework",
    "SGPA_CALC": "SGPA_calc",
    "GRADE_NAME": "GradeName",
    "GRADE_PTS": "GradePts",
    "LEVEL_WEIGHT": "LevelWeight"
}

df = df_raw.rename(columns=rename_map)[list(rename_map.values())]
df.head()

,REGNO,ModuleCode,ModuleName,PassFail,Remarks,MC,GPA_calc,CGPA_calc,Marks,PracticalCW,Coursework,SGPA_calc,GradeName,GradePts,LevelWeight
0,100001,PB-1501,MELAYU ISLAM BERAJA,PASS,NaN,4,Y,Y,73.0,2.4,0.8,Y,C+,3.0,0.2
1,100001,LE-1503,ACADEMIC READING AND WRITING SKILLS,PASS,NaN,4,Y,Y,66.3,2.4,0.8,Y,C+,3.0,0.2
2,100001,AH-2309,INDONESIA IN THE 20TH CENTURY FROM A POLITICAL...,PASS,NaN,4,Y,Y,51.2,1.2,0.8,Y,D,1.5,0.2
3,100001,AH-1201,THE STATE AND SOCIETY IN WORLD CIVILIZATIONS,PASS,NaN,4,Y,Y,67.3,2.4,0.8,Y,C+,3.0,0.2
4,100002,AH-1201,THE STATE AND SOCIETY IN WORLD CIVILIZATIONS,PASS,NaN,4,Y,Y,62.6,2.0,0.8,Y,C,2.5,0.2

In [26]:
df["PassFail"] = df["PassFail"].fillna("Unknown").str.strip()
df["GradeName"] = df["GradeName"].fillna("Unknown").str.strip()
df["Remarks"] = df["Remarks"].fillna("None")

In [27]:
def map_passfail(x):
    if pd.isna(x) or x == "Unknown":
        return -1
    if str(x).upper() == "PASS":
        return 1
    if str(x).upper() == "FAIL":
        return 0
    return -1  # catch-all

df["PassFailBinary"] = df["PassFail"].apply(map_passfail)
df["PassFailBinary"].value_counts()

PassFailBinary
 1    2889
 0      45
-1      42
Name: count, dtype: int64

In [28]:
df_summary = df.groupby("REGNO").agg({
    "ModuleCode": "count",
    "PassFailBinary": lambda x: (x==1).mean(),   # pass rate
    "Marks": "mean",
    "GradePts": "mean"
}).reset_index()

df_summary = df_summary.rename(columns={
    "ModuleCode": "TotalModules",
    "PassFailBinary": "PassRate",
    "Marks": "AvgMarks",
    "GradePts": "AvgGradePts"
})

df_summary.head()

    REGNO  TotalModules  PassRate  AvgMarks  AvgGradePts
0  100001             4       1.0     64.45        2.625
1  100002             4       1.0     64.55        2.500
2  100003             5       1.0     60.78        2.400
3  100004             5       1.0     72.74        3.700
4  100005             5       1.0     73.90        3.300

In [29]:
out_path_detail = OUT_DIR / "transcript_clean.csv"
out_path_summary = OUT_DIR / "transcript_summary.csv"

df.to_csv(out_path_detail, index=False)
df_summary.to_csv(out_path_summary, index=False)

print("Saved:", out_path_detail)
print("Saved:", out_path_summary)

Saved: C:\Users\User\Desktop\Final Year Project\22b6023 Muizzul\3 Processed Data\transcript_clean.csv
Saved: C:\Users\User\Desktop\Final Year Project\22b6023 Muizzul\3 Processed Data\transcript_summary.csv